config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :admin do
    resources :users do
      member do
        get :assign_role
        patch :update_role
        delete :destroy
      end
    end
    resources :profiles
  end
  resources :profiles do
    resources :inquires, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  end
  get "dashboard", to: "dashboards#show"
  root to: "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquire.rb
class Inquire < ApplicationRecord
  belongs_to :profile
  belongs_to :user

  has_many_attached :images

  enum status: { not_verified: 'Not Verified', solved: 'Solved', not_solved: 'Not Solved' }

  validates :date_taken, :city_taken, :country_taken, presence: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_many_attached :images
  has_many :inquires, dependent: :destroy

  def age
    ((Time.zone.now - date_of_birth.to_time) / 1.year.seconds).floor if date_of_birth
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable

  validates :email, presence: true, uniqueness: true

  after_create :assign_default_role

  private

  def assign_default_role
    self.add_role(:regular) if self.roles.blank?
  end
end

app/controllers/admin/profiles_controller.rb
class Admin::ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  def show
  end

  def new
    @profile = Profile.new
  end

  def edit
  end

  def create
    @profile = Profile.new(profile_params)
    if @profile.save
      redirect_to [:admin, @profile], notice: 'Profile was successfully created.'
    else
      render :new, alert: 'Profile could not be created.'
    end
  end

  def update
    if @profile.update(profile_params)
      redirect_to [:admin, @profile], notice: 'Profile was successfully updated.'
    else
      render :edit, alert: 'Profile could not be updated.'
    end
  end

  def destroy
    @profile.destroy
    redirect_to dashboard_path, notice: 'Profile was successfully destroyed.'
  end

  private
  def set_profile
    @profile = Profile.find(params[:id])
  end

  def profile_params
    params.require(:profile).permit(:name, :date_of_birth, :gender, :city, :country, :nationality, :date_of_disappearance, :city_of_disappearance, :country_of_disappearance, :found, images: [])
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin

  def index
    @users = User.page(params[:page]).per(2)
  end

  def assign_role
    @user = User.find(params[:id])
    @roles = Role.all
  end

  def update_role
    user = User.find(params[:id])
    user.roles.delete_all
    params[:roles].each do |role|
      user.add_role(role)
    end if params[:roles].present?
    redirect_to admin_users_path, notice: 'Roles updated successfully.'
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path, notice: 'User was successfully deleted.'
  end

  private

  def require_admin
    unless current_user.has_role?(:admin)
      redirect_to root_path, alert: 'Unauthorized access!'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboards_controller.rb
class DashboardsController < RestrictedAccessController
  def show
    @profiles = Profile.page(params[:page]).per(3)
  end
end

app/controllers/inquires_controller.rb
class InquiresController < ApplicationController
  before_action :set_inquire, only: [:show, :edit, :update, :destroy]
  def index
    @profile = Profile.find(params[:profile_id])
    @inquires = @profile.inquires.page(params[:page]).per(3)

  end

  def new
    @profile = Profile.find(params[:profile_id])
    @inquire = Inquire.new
  end

  def create
    @profile = Profile.find(params[:profile_id])
    @inquire = @profile.inquires.new(inquire_params)
    @inquire.user = current_user

    if @inquire.save
      similarity = fetch_similarity(@profile.images, @inquire.images)
      if similarity >= 0.5
        status = 'Solved'
      elsif similarity > 0.25
        status = 'Not Verified'
      else
        status = 'Not Solved'
      end
      if @inquire.update(similarity: similarity, status: status)
        redirect_to [:admin, @profile], notice: 'Your inquiry has been sent successfully and similarity updated.'
      else
        flash.now[:alert] = 'Failed to update similarity: ' + @inquire.errors.full_messages.join(', ')
        render :new, status: :unprocessable_entity
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @inquire.update(inquire_params)
      redirect_to profile_inquire_path(@inquire.profile, @inquire), notice: 'Inquiry was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @inquire.destroy
    redirect_to profile_inquires_path(@inquire.profile), notice: 'Inquiry was successfully deleted.'
  end

  private

  require 'faraday'
  require 'json'

  def fetch_similarity(profile_images, inquiry_images)
    url = 'https://28d5-188-24-100-23.ngrok-free.app/batch_images_similarity'
    conn = Faraday.new(url) do |f|
      f.request :multipart
      f.adapter Faraday.default_adapter
    end

    payload = {
      'imageList1' => convert_to_uploads(profile_images),
      'imageList2' => convert_to_uploads(inquiry_images)
    }

    payload.each do |key, files|
      files.each do |file|
        logger.info "File prepared for upload: #{file.original_filename}"
      end
    end

    response = conn.post do |req|
      req.body = {}
      payload.each do |key, files|
        files.each_with_index do |file, index|
          req.body["#{key}"] = Faraday::FilePart.new(file.path, file.content_type, file.original_filename)
        end
      end
    end

    result = JSON.parse(response.body)
    logger.info "Response received: #{result}"
    result['similarity']
  rescue => e
    logger.error "Failed to call MPAIFR API: #{e.message}"
    0.0
  end

  def convert_to_uploads(attachments)
    attachments.map do |attachment|
      file_path = ActiveStorage::Blob.service.path_for(attachment.key)
      logger.info "Accessing file at: #{file_path}"
      if File.exist?(file_path)
        Faraday::UploadIO.new(file_path, attachment.content_type, File.basename(file_path))
      else
        logger.error "File does not exist at path: #{file_path}"
        nil
      end
    end.compact
  end

  def set_inquire
    @inquire = Inquire.find(params[:id])
  end

  def inquire_params
    params.require(:inquire).permit(:date_taken, :city_taken, :country_taken, :status, :similarity, images: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :check_signed_in

  def home
  end

  private

  def check_signed_in
    redirect_to(dashboard_path) if signed_in?
  end
end

app/controllers/restricted_access_controller.rb
class RestrictedAccessController < ApplicationController
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_is_admin?
    user_signed_in? && current_user.has_role?(:admin)
  end

  def toast_klass(flash_message_klass)
    case flash_message_klass.to_sym
    when :alert
      "toast align-items-center bg-danger border-0"
    else
      "toast align-items-center bg-success border-0"
    end
  end
end

app/helpers/inquires_helper.rb
module InquiresHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/admin/profiles/_form.html.slim
= simple_form_for [:admin, @profile], html: { multipart: true, class: "form-horizontal" } do |f|
  = f.error_notification

  - if @profile.errors.any?
    .alert.alert-danger
      ul
        - @profile.errors.full_messages.each do |message|
          li = message

  .form-group.row
    = f.label :name, class: 'col-sm-3 col-form-label'
    .col-sm-9
      = f.input :name, label: false, input_html: { class: 'form-control' }

  .form-group.row
    = f.label :date_of_birth, class: 'col-sm-3 col-form-label'
    .col-sm-9
      = f.input :date_of_birth, as: :date, start_year: Date.today.year - 100, end_year: Date.today.year, order: [:day, :month, :year], label: false, input_html: { class: 'form-control custom-select' }

  .form-group.row
    = f.label :gender, class: 'col-sm-3 col-form-label'
    .col-sm-9
      = f.input :gender, collection: ['Male', 'Female', 'Other'], label: false, input_html: { class: 'form-control custom-select' }

  .form-group.row
    = f.label :nationality, class: 'col-sm-3 col-form-label'
    .col-sm-9
      = f.input :nationality, label: false, input_html: { class: 'form-control' }

  .form-group.row
    = f.label :date_of_disappearance, class: 'col-sm-3 col-form-label'
    .col-sm-9
      = f.input :date_of_disappearance, as: :date, start_year: Date.today.year - 100, end_year: Date.today.year, order: [:day, :month, :year], label: false, input_html: { class: 'form-control custom-select' }

  .form-group.row
    = f.label :city_of_disappearance, class: 'col-sm-3 col-form-label'
    .col-sm-9
      = f.input :city_of_disappearance, as: :string, label: false, input_html: { class: 'form-control' }

  .form-group.row
    = f.label :country_of_disappearance, class: 'col-sm-3 col-form-label'
    .col-sm-9
      = f.input :country_of_disappearance, as: :country, priority: ['Romania'], label: false, input_html: { class: 'form-control custom-select' }

  .form-group.row
    = f.label :found, class: 'col-sm-3 col-form-label'
    .col-sm-9
      .form-check
        = f.input :found, as: :boolean, label: false, input_html: { class: 'form-check-input', style: 'transform: scale(1.5);' }

  .form-group.row
    = f.label :images, class: 'col-sm-3 col-form-label'
    .col-sm-9
      = f.input :images, as: :file, label: false, input_html: { multiple: true, accept: 'image/*', class: 'form-control-file' }

  .form-actions
    = f.button :submit, class: 'btn btn-secondary'

app/views/admin/profiles/edit.html.slim
div.w-100
  = render(partial: "common/navbar")

  div.container.mt-3
    .row.justify-content-center
      .col-md-8
        .btn-toolbar.mt-3
          = link_to admin_profile_path(@profile), class: "btn btn-primary mr-2" do
            i.fas.fa-arrow-left
            |  Back
        h2.text-left.mt-3 Edit Profile
        == render 'form'

app/views/admin/profiles/new.html.slim
div.w-100
  = render(partial: "common/navbar")

  div.container.mt-3
    .row.justify-content-center
      .col-md-8
        h2.text-left New Profile
        == render 'form'

        .btn-toolbar.mt-3
          = link_to dashboard_path, class: "btn btn-primary mr-2" do
            i.fas.fa-arrow-left
            |  Back

app/views/admin/profiles/show.html.slim
div.w-100
  = render(partial: "common/navbar")

  div.container.mt-3
    .btn-toolbar.mt-3.p-1
      = link_to dashboard_path, class: "btn btn-primary mr-2" do
        i.fas.fa-arrow-left
        |  Back
    .row
      .col-md-6
        - if @profile.images.attached?
          .d-flex.flex-wrap
            - @profile.images.limit(4).each do |image|
              = image_tag(image.variant(resize_to_fill: [100, 100]), class: "img-fluid p-1", style: "flex: 1 0 50%")
      .col-md-6
        .card-body
          h4.card-text.strong
            strong Profile #
            = @profile.id
          h4.card-text.mb-4
            - if @profile.found
              span.badge.bg-success.text-white = 'Found'
            - else
              span.badge.bg-danger.text-white = 'Not Found'
          - if user_is_admin?
            p.card-text
              strong.mr-2 Name:
              = @profile.name
          p.card-text
            strong.mr-2 Gender:
            = @profile.gender
          p.card-text
            strong.mr-2 Age:
            = @profile.age
          p.card-text
            strong.mr-2 Nationality:
            span = @profile.nationality

          - if user_is_admin?
            p.card-text
              strong.mr-2 Date of Birth:
              span = @profile.date_of_birth.strftime('%d %b %Y')
            p.card-text
              strong.mr-2 Date of Disappearance:
              span = @profile.date_of_disappearance.strftime('%d %b %Y') if @profile.date_of_disappearance.present?
            p.card-text
              strong.mr-2 City of Disappearance:
              span = @profile.city_of_disappearance
            p.card-text
              strong.mr-2 Country of Disappearance:
              span = @profile.country_of_disappearance
          .btn-toolbar.mt-3
            = link_to new_profile_inquire_path(@profile), class: "btn btn-primary mr-2 mt-2" do
              i.fas.fa-file
              |  Send Inquiry
            - if user_is_admin?
              = link_to profile_inquires_path(@profile), class: "btn btn-primary mt-2" do
                i.fas.fa-file
                |  View Inquiries
          .btn-toolbar.mt-3
            - if user_is_admin?
              = link_to edit_admin_profile_path(@profile), class: "btn btn-secondary mr-2 mt-2" do
                i.fas.fa-edit
                |  Edit
              = link_to admin_profile_path(@profile), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger mt-2" do
                i.fas.fa-trash-alt
                |  Delete

  div.container.mt-1
    - @profile.images.offset(4).each_slice(8) do |image_group|
      .row
        .col-md-6
          .d-flex.flex-wrap
            - (image_group[0,4] || []).each do |image|
              = image_tag(image.variant(resize_to_fill: [100, 100]), class: "img-fluid p-1", style: "flex: 1 0 50%")
        .col-md-6
          .d-flex.flex-wrap
            - (image_group[4,4] || []).each do |image|
              = image_tag(image.variant(resize_to_fill: [100, 100]), class: "img-fluid p-1", style: "flex: 1 0 50%")

app/views/admin/users/assign_role.html.slim
div.w-100
  = render(partial: "common/navbar")

  div.container.mt-3
    .btn-toolbar.mt-3
    = link_to admin_users_path, class: "btn btn-primary mr-2" do
      i.fas.fa-arrow-left
      |  Back
    h2.text-left.mt-3 Change Role
    = form_with(model: [:admin, @user], url: update_role_admin_user_path(@user), local: true, method: :patch) do |form|
      .row
        .col-md-12
          - @roles.each do |role|
            .form-group.row
              .col-sm-3
                = label_tag dom_id(role), role.name, class: 'col-form-label'
              .col-sm-9
                .form-check
                  = check_box_tag 'roles[]', role.name, @user.has_role?(role.name), id: dom_id(role), class: 'form-check-input', style: 'transform: scale(1.5); margin-top: 1rem;'

      .form-actions.mt-4
        = form.submit 'Update Roles', class: 'btn btn-secondary'

app/views/admin/users/index.html.slim
div.w-100
  = render(partial: "common/navbar")

  div.container.mt-3
    h2.text-left Users Role Management
    div.table-responsive
      table.table.table-hover.table-light.shadow.rounded
        thead.thead-light
          tr
            th Email
            th Roles
            th Actions
        tbody
          - @users.each do |user|
            tr.text-dark
              td = user.email
              td
                - user.roles.each do |role|
                  - case role.name
                    - when 'admin'
                      span.badge.bg-danger.text-white.mr-2 = role.name
                    - when 'regular'
                      span.badge.bg-primary.text-white.mr-2 = role.name
                    - else
                      span.badge.bg-info.text-white.mr-2 = role.name
              td.mt-2
                = link_to assign_role_admin_user_path(user),
                        class: 'btn btn-primary btn-sm mr-2 mb-2' do
                  i.fas.fa-pencil-alt
                  |  Change Role
                = link_to admin_user_path(user),
                        method: :delete,
                        data: { confirm: "Are you sure you want to delete this user?" },
                        class: 'btn btn-danger btn-sm mr-2 mb-2' do
                  i.fas.fa-trash-alt
                  |  Delete
    div.d-flex.justify-content-center.mt-4
      = paginate @users, theme: 'bootstrap-5'

app/views/common/_flash_message.html.slim
div class=toast_klass(klass) role="alert" aria-live="assertive" aria-atomic="true" style="min-width: 350px;"
  .d-flex
    .toast-body
      = message

app/views/common/_flash_messages.html.slim
div.mt-5 aria-live="polite" aria-atomic="true" style="position: relative;"
  div style="position: absolute; top: 20px; right: 20px;"
    - flash.each do |(klass, message)|
      = render(partial: "common/flash_message", locals: { klass: klass, message: message })

app/views/common/_navbar.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-secondary.sticky-top
  = link_to(t("app_name"), root_path, class: "navbar-brand")
  button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"
    span.navbar-toggler-icon
  #navbarNav.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      li.nav-item.m-2
        = link_to(t("dashboard"), dashboard_path)
      - if user_is_admin?
        li.nav-item.m-2
          = link_to("User Management", admin_users_path)

    .nav-item
      = link_to("Logout", destroy_user_session_path, method: :delete)

app/views/dashboards/show.html.slim
div.w-100
  = render(partial: "common/navbar")


  div.container.mt-3
    h2.text-left Profiles Dashboard
    - @profiles.each do |profile|
      .card.mb-3.mt-3
        .row.m-3
          - if profile.images.attached?
            .col-md-6
              .d-flex.flex-wrap
                - profile.images.limit(4).each do |image|
                  = image_tag(image.variant(resize_to_fill: [100, 100]), class: "img-fluid p-1", style: "flex: 1 0 50%")
          .col-md-6
            .card-body.text-dark
              h4.card-text.strong
                strong Profile #
                = profile.id
              h4.card-text.mb-4
                - if profile.found
                  span.badge.bg-success.text-white = 'Found'
                - else
                  span.badge.bg-danger.text-white = 'Not Found'
              - if user_is_admin?
                p.card-text
                  strong.mr-2 Name:
                  = profile.name ? profile.name : 'Unknown'
              p.card-text
                strong.mr-2 Gender:
                = profile.gender
              p.card-text
                strong.mr-2 Age:
                = profile.age
              p.card-text
                strong.mr-2 Nationality:
                = profile.nationality
              - if user_is_admin?
                p.card-text
                  strong.mr-2 Date of Birth:
                  = profile.date_of_birth.strftime("%d %b %Y") if profile.date_of_birth.present?
                p.card-text
                  strong.mr-2 Date of Disappearance:
                  = profile.date_of_disappearance.strftime("%d %b %Y") if profile.date_of_disappearance.present?
                p.card-text
                  strong.mr-2 City of Disappearance:
                  = profile.city_of_disappearance
                p.card-text
                  strong.mr-2 Country of Disappearance:
                  = profile.country_of_disappearance
              .btn-toolbar.mt-5
                = link_to admin_profile_path(profile), class: "btn btn-primary mr-2 mt-2" do
                  i.fas.fa-eye
                  |  View
                = link_to new_profile_inquire_path(profile), class: "btn btn-primary mr-2 mt-2" do
                  i.fas.fa-file
                  |  Send Inquiry
                - if user_is_admin?
                  = link_to profile_inquires_path(profile), class: "btn btn-primary mr-2 mt-2" do
                    i.fas.fa-file
                    |  View Inquiries

    div.d-flex.justify-content-center.mt-4
      = paginate @profiles, theme: 'bootstrap-5'
    - if user_is_admin?
      = link_to new_admin_profile_path, class: "btn btn-primary btn-floating position-fixed", style: "bottom: 20px; right: 20px;" do
        i.fas.fa-plus

app/views/inquires/edit.html.slim
div.w-100
  = render(partial: "common/navbar")

  div.container.mt-3
    .btn-toolbar.mt-3
      = link_to profile_inquire_path(@inquire), class: "btn btn-primary mr-2" do
        i.fas.fa-arrow-left
        |  Back
  div.container.mt-3
    h2.text-left Edit Inquiry
    = simple_form_for([@inquire.profile, @inquire], html: { multipart: true, class: "form-horizontal" }) do |f|
      = f.error_notification

      - if user_is_admin?
        .form-group.row
          = f.label :status, class: 'col-sm-3 col-form-label'
          .col-sm-9
            = f.select :status, Inquire.statuses.keys.map { |status| [status.humanize, status] }, {}, { class: 'form-control custom-select' }
      .form-actions.mt-4
        = f.button :submit, 'Update Status', class: 'btn btn-secondary'

app/views/inquires/index.html.slim
div.w-100
  = render(partial: "common/navbar")

  div.container.mt-3
    .btn-toolbar.mt-3.p-1
      = link_to admin_profile_path(@profile), class: "btn btn-primary mr-2" do
        i.fas.fa-arrow-left
        |  Back
    h2.text-left.mt-3 All inquiries
    div.table-responsive
      table.table.table-hover.table-light.shadow.rounded
        thead.thead-light
          tr
            th Date Taken
            th City Taken
            th Country Taken
            th Profile
            th Submitted by
            th Status
            th Actions
        tbody
          - @inquires.each do |inquire|
            tr.text-dark
              td = inquire.date_taken
              td = inquire.city_taken
              td = inquire.country_taken
              td = link_to inquire.profile.name, admin_profile_path(inquire.profile)
              td = inquire.user.email
              td
                - case inquire.status
                  - when 'not_verified'
                    span.badge.bg-warning.text-white = 'Not Verified'
                  - when 'solved'
                    span.badge.bg-success.text-white = 'Solved'
                  - when 'not_solved'
                    span.badge.bg-danger.text-white = 'Not Solved'
              td
                = link_to [inquire.profile, inquire], class: 'btn btn-primary btn-sm mr-2' do
                  i.fas.fa-eye
                  |  Show
                = link_to edit_profile_inquire_path(inquire.profile, inquire), class: 'btn btn-secondary btn-sm mr-2' do
                  i.fas.fa-edit
                  |  Update Status
                = link_to profile_inquire_path(inquire.profile, inquire), method: :delete, data: { confirm: "Are you sure you want to delete this inquiry?" }, class: 'btn btn-danger btn-sm' do
                  i.fas.fa-trash-alt
                  |  Delete

    div.d-flex.justify-content-center.mt-4
      = paginate @inquires, theme: 'bootstrap-5'

app/views/inquires/new.html.slim
div.w-100
  = render(partial: "common/navbar")

  div.container.mt-3
    .row.justify-content-center
      .col-md-8
        .btn-toolbar.mt-3
          = link_to admin_profile_path(@profile), class: "btn btn-primary mr-2" do
            i.fas.fa-arrow-left
            |  Back
        h1.text-left.mt-3 Send Inquiry
        = simple_form_for([@profile, @inquire], html: { multipart: true, class: "form-horizontal" }) do |f|
          = f.error_notification

          - if @inquire.errors.any?
            .alert.alert-danger
              ul
                - @inquire.errors.full_messages.each do |message|
                  li = message

          .form-group.row
            = f.label :date_taken, class: 'col-sm-3 col-form-label'
            .col-sm-9
              = f.input :date_taken, as: :date, label: false, input_html: { class: 'form-control custom-select' }

          .form-group.row
            = f.label :city_taken, class: 'col-sm-3 col-form-label'
            .col-sm-9
              = f.input :city_taken, label: false, input_html: { class: 'form-control' }

          .form-group.row
            = f.label :country_taken, class: 'col-sm-3 col-form-label'
            .col-sm-9
              = f.input :country_taken, label: false, input_html: { class: 'form-control custom-select' }

          .form-group.row
            = f.label :images, class: 'col-sm-3 col-form-label'
            .col-sm-9
              = f.input :images, as: :file, label: false, input_html: { multiple: true, accept: 'image/*', class: 'form-control-file' }

          .form-actions
            = f.button :submit, "Send", class: 'btn btn-success'

app/views/inquires/show.html.slim
div.w-100
  = render(partial: "common/navbar")

  div.container.mt-3
    .btn-toolbar.mt-3.p-1
      = link_to profile_inquires_path(@inquire.profile), class: "btn btn-primary mr-2" do
        i.fas.fa-arrow-left
        |  Back
    .row
      .col-md-6
        - if @inquire.images.attached?
          .d-flex.flex-wrap
            - @inquire.images.each do |image|
              = image_tag(image.variant(resize_to_fill: [100, 100]), class: "img-fluid p-1", style: "flex: 1 0 50%")
      .col-md-6
        .card-body
          h4.card-text.strong
            strong Inquiry #
            = @inquire.id
          h4.card-text.mb-4
            span.badge class=(@inquire.status == 'solved' ? 'bg-success text-white' : @inquire.status == 'not_verified' ? 'bg-warning text-white' : 'bg-danger text-white') = @inquire.status.humanize
          p.card-text
            strong.mr-2 Date Taken:
            = @inquire.date_taken
          p.card-text
            strong.mr-2 City Taken:
            = @inquire.city_taken
          p.card-text
            strong.mr-2 Country Taken:
            = @inquire.country_taken
          p.card-text
            strong.mr-2 Submitted by:
            = @inquire.user.email

          h4.card-text.strong
            strong.mr-2 Similarity Score:
            span.badge class=(@inquire.similarity >= 0.50 ? 'bg-success text-white' : @inquire.similarity > 0.25 ? 'bg-warning text-white' : 'bg-danger text-white') = sprintf('%.2f%%', @inquire.similarity * 100)

          .btn-toolbar.mt-3
            = link_to admin_profile_path(@inquire.profile), class: "btn btn-light mt-2" do
              i.fas.fa-user
              |  Profile
          .btn-toolbar.mt-3
            = link_to edit_profile_inquire_path(@inquire.profile, @inquire), class: "btn btn-secondary mr-2 mt-2" do
              i.fas.fa-edit
              |  Update Status
              = link_to profile_inquire_path(@inquire.profile, @inquire), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger mt-2" do
                i.fas.fa-trash-alt
                |  Delete

app/views/inquires/update.html.slim
h1 Inquires#update
p Find me in app/views/inquires/update.html.slim

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>MPAIFR</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
  </head>

  <body class="d-flex h-100">
    <%= yield %>
    <%= render(partial: "common/flash_messages") %>
  </body>
</html>

app/views/pages/_pages_footer.html.slim
footer.mt-auto.text-muted.text-center
  .row
    .col
      = link_to(t("github"), "https://github.com/", class: "text-muted text-decoration-none")

app/views/pages/_pages_navigation.html.slim
header.masthead.mb-auto
  nav.nav.nav-masthead.justify-content-center
    = link_to(t("home"), root_path, class: "nav-link")
    = link_to(t("login"), new_user_session_path, class: "nav-link")
    = link_to(t("register"), new_user_registration_path, class: "nav-link")

app/views/pages/home.html.slim
.cover-container.d-flex.w-100.h-100.p-3.mx-auto.flex-column.text-center
  = render(partial: "pages/pages_navigation")

  main.px-3
    h1 = t("app_name")
    p.lead
      = t("app_description")
    .d-grid.gap-2
      = link_to(t("login"), new_user_session_path, class: "btn btn-lg btn-primary fw-bold md-2 mr-3")
      = link_to(t("register"), new_user_registration_path, class: "btn btn-lg btn-secondary fw-bold md-2")

  = render(partial: "pages/pages_footer")